### ISSUE TITLE
Coding Questions

### ISSUE THREAD

**Issue by jackttcoms** [sonicsleuth/mvc-framework-php#15]
Hi SonicSleuth.

I am currently just looking at how all your mvc works and found a few bits i do not fully understand and was wondering if you could clear them up. Thanks very much.

1) In app/core/app.php you have this line: `list($name, $value) = explode('=',$_SERVER['QUERY_STRING']);` where does the `$name` come from? Also can't you use a short list here as well [$name, $value] Thanks 

2) In app/core/app.php, is it possible to merge this line: `$pattern = str_replace(":any", "(.+)", $pattern);` and this line `$pattern = str_replace(":num", "(\d+)", $pattern);` together for less code as can't string replace take arrays?

3) In your app/core/model.php, why do you not have `if (!defined('BASE_PATH')) exit('No direct script access allowed');` and shouldn't it have curly brackets?

4) In app/core/app.php can these if statements be combined? less code. ur the expert.
```
        // Set Method or use default.
        if (isset($this->url[$this->method_index]))
        {
            /**
             * Changed from method_exists() to is_callable() allowing for Classes
             * to offer Private methods that cannot be invoked by dynamic URLs such
             * as /class/private-method/param
             */
            //if(method_exists($this->controller, $this->url[$this->method_index]))
            if (is_callable(array($this->controller, $this->url[$this->method_index])))
            {
                $this->method = $this->url[$this->method_index];
                unset($this->url[$this->method_index]);
            }
        }
```
5) In app/core/app.php there is this in the parseUrl. `return $url = explode('/', $this->url_string);`, what is the $url there for?

6) In app/core/controller.php you have a file exists and then return false. What does the return false do? Is there an error somewhere else? Also regarding functions, is type hinting beneficial? https://mlocati.github.io/articles/php-type-hinting.html
```
    protected function model($model)
    {
        if (file_exists(MODELS_PATH . $model . '.php'))
        {
            require_once MODELS_PATH . $model . '.php';
            return new $model();
        } else {
            return false;
        }
    }
```

and a general security question, is this insecure, in the sense of always validating against logins to make sure pwd is correct?
```
    public function dologin($username, $password) // Check login credentials are correct
    {
        $bind = [':username' => $username];
        $results = $this->db->select('everything_users', 'username = :username', $bind);
        $hashed_password = $results[0]['password'];
        if (password_verify($password, $hashed_password)) {
            return $results;
        }
        return false;
    }
```

And second to last: what is the best way to debug your mvc if just a blank screen shows with no error. This only happens on some hosts, others works perfectly.

And finally, what tools do you use to check your coding security and debugging (thorough scanning) just because you have built such a great mvc and i want to make sure the applications i build using it are secure just like all your code. Btw hope u had a great Christmas & New Years Eve.

Thanks as always, truly grateful for your help and opinion.

**Comment by sonicsleuth** [comment]
Answers to your questions...


   1.

   In app/core/app.php you have this line: list($name, $value) =
   explode('=',$_SERVER['QUERY_STRING']); where does the $name come from?
   Thanks
   list($name, $value) is simply storing the name/value pair of a query
   string such as ?name=value
   list() is assigning $name and $value from the return of the explode()
   function.
   2.

   In app/core/app.php, is it possible to merge this line: $pattern =
   str_replace(":any", "(.+)", $pattern); and this line $pattern =
   str_replace(":num", "(\d+)", $pattern); together for less code as can't
   string replace take arrays?
   Merging these two replacements into a $find, $replace array pattern will
   work but you must maintain the index keys for both arrays to insure the
   $find matches the correct $replace array index.  In this example
   having only two patterns can be merged but if the list gets long it can
   open up for bugs due to index mismatch. Therefore, I default to using
   single lines of code to ensure the pairing is maintained. (Personal
   preference)
   3.

   In your app/core/model.php, why do you not have if
   (!defined('BASE_PATH')) exit('No direct script access allowed');
   That's a bug. It should be there as an added layer of protection. I'll
   updated the framework.

   4.

   In app/core/app.php can these if statements be combined? less code. ur
   the expert.
   It can be combined into a single if() statement.  I chose to nest it
   with comments as a reminder why is_callable() was preferred over
   method_exists().  These get cleaned up at some point when refactoring.
   Short story: I was once asked to change some code in a similar way which
   changed the output of the function. Two years later I was asked to change
   it again. By having my original comments explaining the first change I was
   able to tell the project manager that his new change "reverted" back to the
   "original" process and ask him why? Developers are smart but you will never
   recall every change years later. ;-)

        // Set Method or use default.
        if (isset($this->url[$this->method_index]))
        {
            /**
             * Changed from method_exists() to is_callable() allowing
for Classes
             * to offer Private methods that cannot be invoked by
dynamic URLs such
             * as /class/private-method/param
             */
            //if(method_exists($this->controller,
$this->url[$this->method_index]))
            if (is_callable(array($this->controller,
$this->url[$this->method_index])))
            {
                $this->method = $this->url[$this->method_index];
                unset($this->url[$this->method_index]);
            }
        }


   1. In app/core/app.php there is this in the parseUrl. return $url =
   explode('/', $this->url_string);, what is the $url there for?
   The $url returned by the parseUrl() function will contain an array of
   the parts of the url construct, like /controller/method/param
   We will later process the $url array to find the controller (even if
   it's in a sub-directory), it's method, and pass in any params.
   There is a switch case controlled by a master config value which
   specifies the internal PHP method to use to obtain the URL.

*Regarding Security Testing:*
There are many tools available that perform "Fuzzing" tests as well as good
resources at the OWASP site below.  Using a fuzzer is a good idea. But, you
could also try coding an automated system yourself, as this will boost your
knowledge about php and security issues/loop holes in your php sites.

As you review your code manually for security holes, or while developing
your own test suite, focus on only those parts that allow access from
"outside the system" meaning anything a user might inject into the system
(ie forms, api, image uploads, etc)

Some tools are inexpensive but you will spend time walking the keyboard to
install them. Paid services are available, but are costly $5k+ (per test
session).

Learn about Fuzzing: https://en.wikipedia.org/wiki/Fuzzing
Learn about OWASP: https://www.owasp.org/index.php/Main_Page
OWASP recommended scanning tools:
https://www.owasp.org/index.php/Category:Vulnerability_Scanning_Tools

Hope this helps you learn something new.
Hope your holidays were good too.

*Richard Soares*

**Comment by jackttcoms** [comment]
Thanks very much for your detailed reply. Also without sounding rude you forgot to answer this: (number 6 & the second to last one)

In app/core/controller.php you have a file exists and then return false. What does the return false do? Is there an error somewhere else as in shouldn’t it echo some error saying view file not found. Also regarding functions, is type hinting beneficial? https://mlocati.github.io/articles/php-type-hinting.html

    protected function model($model)
    {
        if (file_exists(MODELS_PATH . $model . '.php'))
        {
            require_once MODELS_PATH . $model . '.php';
            return new $model();
        } else {
            return false;
        }
    }


And second to last: what is the best way to debug your mvc if just a blank screen shows with no error. This only happens on some hosts, others works perfectly

**Comment by sonicsleuth** [comment]
No worries, glad to help. I did not see a #6 as I am responding via email.

My replies follow:

In app/core/controller.php you have a file exists and then return false.
What does the return false do? Is there an error somewhere else as in
shouldn’t it echo some error saying view file not found.

The function returns false so that [you] can check if the model exists when
created it like so: $user = $this->model('User');
Rather than tossing up a Not Found Error from the framework, I allow the
developer to check for it's existence after you create it.  There may be
patterns when the developer may chose to perform some other custom warning
actions on fail.

Also regarding functions, is type hinting beneficial?
https://mlocati.github.io/articles/php-type-hinting.html

Type hinting is one of those arguable religions in development. There are
some design patterns that don't work well with strongly typed functions.
For example, a smart function that accepts a single parameter and then will
internally determine if it was a string, array, object and handle it
appropriately.  It all depends on the project and design pattern.

and a general security question, is this insecure, in the sense of always
validating against logins to make sure pwd is correct?

There are many secure design patterns. Checking the pwd is one way. Another
would be to set a unique session id as you do now.  The extreme is to
refresh the unique session id for every HTTP request, .NET does this to
avoid 1/2 of the man-in-the-middle attacks.  I think of security in this
way - Protect that which others see of value.  If you site contains no
valuable data (ie: exploitable personal data) then a login session is
nothing more than a function to manage User Roles.

And second to last: what is the best way to debug your mvc if just a blank
screen shows with no error. This only happens on some hosts, others works
perfectly

If it is happening on specific hosts (environments) then the debugging is
split between the app and the environment causing the bug a bane for all
developers.  This goes down a long rabbit hole regarding
environment deployment and unit testing against the environment.  For now,
I'd debug manually and maybe put a specific patch in for that specific
environment so BLANK is less meaningless.
Cheers!

*Richard Soares*

**Comment by jackttcoms** [comment]
Thanks again. Also for an update as my host has a very sensitive php environment where they disable alot of things by default. They do not have an automatic error log func so you have to manually enable it yourself but i was wondering in your mvc could you add an optional function where you can enable messages if your host does not do it automatically. Just a thought for better dev environment mode.

```
ini_set ('track_errors', 1); 
ini_set ('log_errors',   1); 
ini_set ('error_log',    'php_error.log'); 
```

Also above you said: For now, I'd debug manually and maybe put a specific patch in for that specific environment so BLANK is less meaningless..... Specific patch what do you mean by this? Thanks. Only data i can get to show is if i go to public/index.php and do an echo 'test'; Also how do you identify the environment. It is a host using CentOS Apache, PHP 7.1, HTTPS. Surely that is the perfect environment (if that is what you mean) for your mvc.

Thanks again as always.

**Comment by sonicsleuth** [comment]
To fix something with a "specific patch" means to identify the issue and
where it resides. Is it in the code or the supporting environment. For
example, one possible reason you are getting a blank page could be that the
mod_rewrite module is NOT enabled in Apache which allows the configuration
in the .htaccess to work properly.  Without it, the whole MVC pattern does
not work.  So in this case, the "patch" would be to enable this Apache
module through your host provider or if you need to do it yourself after
SSH'ing into the server.

Your CentoOS environment should work just fine (IF) all of the required
configurations of those parts are setup properly.  I personally use Ubuntu
vs CentOS but it's all similar in the end.

One possible option, and you will learn a lot, would be to look into Docker
containers.  Using Docker, you will build a local server environment then
place that exact environment onto your host server. This way, every
deployment is EXACT to your specification.  It does take some learning and
trials but development gets better.

For example - Have a look at the Dockerfile in the root of the MVC. You can
see how there are commands to enable the rewrite module in Apache as
typically it's not enabled. If you have Docker installed, and having
provided this Dockerfile in the repository, any developer can "spin up" a
complete server specific for this MVC both locally and in production.

# Enable Apache Rewrite Module
RUN a2enmod rewrite
RUN service apache2 restart

Side note - Also in the root I have provided a Vagrant file as an
alternative for those developers using VirtualBox by Oracle for their
Virtual Machines (old school way).

Finally, using Docker containers gets into the full Deployment testing
process whereby you not only can run code tests but environment tests to
halt deployment if something is not as specified. Of course, containers
also allow for easy scaling of your site (applications) but this gets into
the whole app architecture now.

If you are note familiar with Docker Hub, it's like GitHub for server
environments.  You start by building a Docker container from a base repo
and add to it your configs (see below).

References:
https://www.docker.com/
https://hub.docker.com/

https://www.oracle.com/virtualization/virtualbox/
http://vagrantmanager.com/

Cheers!

*Richard Soares*

**Comment by jackttcoms** [comment]
Thankyou again for your expertise. It is really helpful and insightful. ADD: mod_rewrite is enabled tho as it goes straight to public/index.php where i did an echo 'test'; to check.

My final questions for you and then i will stop commenting on here for a while as i feel like i am spamming your inbox. What coding software do you use? I recently found PhpStorm which is great and highlights lots of things but it's always good to know about others.

And also regarding the error logging idea. Is that something you think would be beneficial for development for example sometimes you see no error on front end but then when u look in your host's auto generated error log you find lots of hidden bugs. Always helpful and just a nice simple addition. Of course optional but what do you think?

```
ini_set ('track_errors', 1); 
ini_set ('log_errors',   1); 
ini_set ('error_log',    'php_error.log'); 
```

... and for the app/core/model.php i add, `<?php if (!defined('BASE_PATH')) { exit('No direct script access allowed'); }`. to add extra layer of security but should that line be placed on every single document throughout the mvc including the view files?

Thanks again as always. 💯

**Comment by sonicsleuth** [comment]
Hi Jack,

PhpStorm is the best tool for PHP development due to its strong intenseness
(code completion).  It's super robust. I've been using it for 6+ years and
still find new features.
If I am doing something quick, I will also use Visual Studio Code (free).
Its is lite but you must install loads of extensions to make it close to
PHPstorm.

The developer debugging options sounds good.  I left much of these options
out of the MVC framework so that it focused on Routing, Views,
Controllers.  Everything else could become extensions (added features) for
any specific project.  It helps keep the base as small as possible.

I would NOT add the check for the BASE_PATH to Views as it may cause issues
with nested Views or some unpredicted pattern.

Finally, below is my personal email.  Feel free to directly email here vs
thru Github.  I trust you now that your not going to spam my inbox ;-)

*Richard Soares*
soares.richard@gmail.com

**Comment by jackttcoms** [comment]
Excellent. I am using the right software. I have also installed a plugin called SolarLint for PHPStorm which picks up a few things. 👍 Do you know any other good plugins?

Ah ok, and how about helper files? If not is it just model, controller, core files?

And: Quick question, you know how you do not use curly brackets for certain if statements 'n' foreach statements, is that a personal coding preference? Thanks

Finally... wow thankyou very much. Again really appreciate the help and advice given. Ye don't worry, i'm a considerate emailer. 👍

**Comment by sonicsleuth** [comment]
SolarLint is nice.

No need to add the protection to the helper files as they are only accessed
by the internal MVC itself.

*Richard Soares*
