### ISSUE TITLE
Routes problem

### ISSUE THREAD

**Issue by surepeps** [sonicsleuth/mvc-framework-php#16]
I tried to create a controller named "Newuser' and also a view named "newuserview" but I tried Linking the view page to the controller "Newuser'" under index function but could not view it with the routes or
$route["regnewuser"] = "newuser"; 

It's loading error page

**Comment by sonicsleuth** [comment]
Please post your Controler code so that I can review it.

That said, here are a few debug tips:
1. Remapping URLs is only required if the build-in Controller detection within a URL is not sufficient - http://example.com/controller/method/param1/param2
2. If your Controler file name is Newuser try removing the $route["regnewuser"] = "newuser"; and just format your url as such http://example.com/newuser  --- By default the framework will try to locate a Controller file named Newuser and call the index() method if no other method is specified in the URL.

**Comment by surepeps** [comment]
![Screenshot (199)](https://user-images.githubusercontent.com/31157177/68631431-2b63ae00-04eb-11ea-9864-9ddfb2305a54.png)

**Comment by surepeps** [comment]
$route['newuse'] = 'newuser';

**Comment by surepeps** [comment]
and also even for the existing controller like "Docs" and "Examples" i could not view them it was just showing object not found pls help me out

**Comment by sonicsleuth** [comment]
Considering that both Docs and Examples are not working I'd say there is some environment issue with your set up. Which version of PHP are you using? The framework has been tested on 7.1+.

Try placing a simple  die("ok here")  before and after the $this->view('newuserview') to see if it's the view() function that has issues.

**Comment by surepeps** [comment]
PHP 7.3

**Comment by surepeps** [comment]
URI:- http://localhost/newframe/newuser

newframe = The project Folder name
newuser = Controller name




![Screenshot (202)](https://user-images.githubusercontent.com/31157177/68638647-881e9300-0502-11ea-9583-ad7825b75bd2.png)

**Comment by surepeps** [comment]
Have tried to deploy the framework online to check if my localserver is the cause but its still yhe same thing ........ see the below trials and their errors


http://frame.tijani.dervac.com/         =>        this shows all the root files until i click on public
http://frame.tijani.dervac.com/public/        =>         this show the default controller index
http://frame.tijani.dervac.com/public/newuser/     =>      Shows NOT FOUND
http://frame.tijani.dervac.com/newuser/      =>      Shows NOT FOUND
http://frame.tijani.dervac.com/public/index,php/newuser/       =>       Shows The dafault controller index

**Comment by sonicsleuth** [comment]
So it looks like the issue is with your Apache Configuration. I am assuming here that you DID NOT use the included Vagrant/Boostrap or Docker files to build your web server.

Apache needs to be configured to serve the site from the /public/ directory, NOT the root of the application directory.  This way no one has access to the inner working of the framework on the internet.  

The URLs lead me to this conclusion...
http://frame.tijani.dervac.com/ => Should NEVER display the Application Root
http://frame.tijani.dervac.com/public/ => this shows the default controller index... because "public" is not a Controller so the framework displayed the default Controller "Home" and Method "index" (See /app/config/config.php)

Have a look at the /bootstrap.sh file (lines 14-26) which are the .htaccess setting you need to set up and enable within Apache. If you build your own server, you will need to make this adjustment manually.

TIP: To see just what the framework is parsing from your URL look in /app/core/App.php (line 54). If you dump the value of $this->url after that line you will see the parts ie: controller, method, params.  If it looks wrong that's because of the above issue.
